name: build
on:
    push:
        branches:
            - develop
            - master
    pull_request: ~
jobs:
    build:
        if: github.event_name != 'pull_request' || github.base_ref == 'refs/heads/master' || github.base_ref == 'refs/heads/develop'
        strategy:
            matrix:
                php-versions: ['8.1', '8.2']
        name: Continues Integration (PHP ${{ matrix.php-versions }})
        runs-on: ubuntu-latest
        steps:
            # Checkout project
            - name: Checkout
              uses: actions/checkout@v2
            # Install php & composer
            - name: Setup PHP, extensions and composer with shivammathur/setup-php
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php-versions }}
                  extensions: mbstring, xml, ctype, iconv, intl, dom, filter, iconv, json
              env:
                  update: true
            - name: Check PHP Version
              run: php -v
            # Composer
            - name: Validate composer.json and composer.lock
              run: composer validate
            - name: Get composer cache directory
              id: composer-cache
              run: echo "::set-output name=dir::$(composer config cache-files-dir)"
            - name: Cache composer dependencies
              uses: actions/cache@v1
              with:
                  path: ${{ steps.composer-cache.outputs.dir }}
                  key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
                  restore-keys: ${{ runner.os }}-composer-
            - name: Install Composer dependencies
              run: composer install
            # Coding standard
            - name: Coding standards checks (php_codesniffer)
              run: bin/phpcs -n --colors --error-severity=1
            # PhpUnit
            - name: PhpUnit
              run: bin/simple-phpunit --coverage-clover ./clover.xml
            # Generate test coverage badge (only master branch)
            - name: Generate test coverage badge
              uses: timkrase/phpunit-coverage-badge@v1.2.0
              if: ${{ github.ref == 'refs/heads/master' }}
              with:
                  coverage_badge_path: coverage.svg
                  push_badge: false
            # Update test coverage badge (only master branch)
            - name: update badge
              uses: exuanbo/actions-deploy-gist@v1
              if: ${{ github.ref == 'refs/heads/master' }}
              with:
                  token: ${{ secrets.GIST_COVERAGE_BADGE }}
                  gist_id: 210e582b8ded2b1013aeab92bad9f5fe
                  file_path: coverage.svg
                  file_type: binary
